name: viserremit
services:
- name: web
  source_dir: /
  github:
    repo: yourusername/viserremit
    branch: main
    deploy_on_push: true
  run_command: |
    cd core && php artisan serve --host=0.0.0.0 --port=8080
  build_command: |
    cd core && composer install --no-dev --optimize-autoloader
    cd core && npm ci && npm run build
    cd core && php artisan config:cache
    cd core && php artisan route:cache
    cd core && php artisan view:cache
    cd core && php artisan migrate --force
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  environment_slug: php
  envs:
  - key: APP_NAME
    value: "ViserRemit"
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: ${APP_URL}
  - key: APP_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_PORT
    value: ${db.PORT}
  - key: DB_DATABASE
    value: ${db.DATABASE}
  - key: DB_USERNAME
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: CACHE_DRIVER
    value: file
  - key: FILESYSTEM_DISK
    value: local
  - key: QUEUE_CONNECTION
    value: database
  - key: SESSION_DRIVER
    value: database
  - key: SESSION_LIFETIME
    value: "120"
  - key: MAIL_MAILER
    value: smtp
  - key: MAIL_HOST
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MAIL_PORT
    value: "587"
  - key: MAIL_USERNAME
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MAIL_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MAIL_ENCRYPTION
    value: tls

databases:
- name: db
  engine: MYSQL
  version: "8"
  size: basic-xs
  num_nodes: 1

static_sites:
- name: assets
  source_dir: core/public
  index_document: index.php
  routes:
  - path: /assets
