name: viserremit
services:
- name: web
  source_dir: /
  github:
    repo: yourusername/viserremit
    branch: main
    deploy_on_push: true
  build_command: |
    cd core && composer install --no-dev --optimize-autoloader
    cd core && php artisan key:generate --force
    cd core && php artisan migrate --force
    chmod -R 755 .
    chmod -R 777 core/storage
    chmod -R 777 core/bootstrap/cache
  instance_count: 1
  instance_size_slug: basic-xxs
  environment_slug: php
  envs:
  - key: APP_NAME
    value: "ViserRemit"
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: ${APP_URL}
  - key: APP_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    value: db-mysql-nyc3-71993-do-user-22832758-0.k.db.ondigitalocean.com
  - key: DB_PORT
    value: "25060"
  - key: DB_DATABASE
    value: defaultdb
  - key: DB_USERNAME
    value: doadmin
  - key: DB_PASSWORD
    value: AVNS_uifyEPdbfSOU8MqN8cu
  - key: CACHE_DRIVER
    value: file
  - key: FILESYSTEM_DISK
    value: local
  - key: QUEUE_CONNECTION
    value: database
  - key: SESSION_DRIVER
    value: database
  - key: SESSION_LIFETIME
    value: "120"
  - key: MAIL_MAILER
    value: smtp
  - key: MAIL_HOST
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MAIL_PORT
    value: "587"
  - key: MAIL_USERNAME
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MAIL_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MAIL_ENCRYPTION
    value: tls
